name: Sinead Howland Career Coaching
favicon: null
layout_spectrum: 0.25904
typography_spectrum: 0.48989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#69c9c8'
    - '#01a8a6'
    - '#231f20'
    - '#5c5b5b'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
