name: Sinead Howland Career Coaching
favicon: null
layout_spectrum: 0.8531952744815499
typography_spectrum: 0.85939
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6dc9c7'
    - '#231f20'
    - '#595859'
    - '#8f8e8f'
  brandStrength: 0.5
  lightness: 0.24720060313120484
  saturation: 0.030252118362113833
  rhythmicContrast: 0.3478590154554695
purpose: []
